Repository SejongPeer/peer_v2, pull requests merged in 2024-10, with the labels that each got.

#16 feat: [5] 회원가입 전체 디자인 수정
  .env
  .gitignore
  app/globals.css
  components.json
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/backArrow.png
  src/assets/images/backArrow_Black.png
  src/assets/images/banner1.webp
  src/assets/images/banner2.webp
  src/assets/images/banner3.webp
  src/assets/images/checkedBtn.png
  src/assets/images/filledCheck.png
  src/assets/images/rightArrow.png
  src/assets/images/uncheckedBtn.png
  src/assets/images/unfilledCheck.png
  src/assets/images/user.png
  src/assets/images/user_black.png
  src/components/banner.tsx
  src/components/header.tsx
  src/components/loginHeader.tsx
  src/components/register/Major.tsx
  src/components/register/genderToggleButton.tsx
  src/components/register/majorDropDown.tsx
  src/components/register/registerStep1.tsx
  src/components/register/registerStep2.tsx
  src/components/register/registerStep3.tsx
  src/components/register/registerStep3_1.tsx
  src/components/register/registerStep3_2.tsx
  src/components/register/registerStep4.tsx
  src/components/subHeader.tsx
  src/components/ui/sonner.tsx
  src/index.css
  src/lib/schema/auth.schema.ts
  src/lib/utils.ts
  src/lib/utils/auth.ts
  src/pages/home-page.tsx
  src/pages/login-page.tsx
  src/pages/register-page.tsx
  src/services/apis/user.service.ts
  src/services/axios-instance.ts
  src/styles/global-styles.ts
  src/theme.ts
  src/types/user.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: style

#18 feat: [6] lazy loading 적용
  package-lock.json
  package.json
  src/components/register/registerStep3_1.tsx
  src/components/register/registerStep4.tsx
  src/index.css
  src/pages/login-page.tsx
  src/services/apis/user.service.ts
  src/store/useRegisterStore.tsx
  src/theme.ts
  src/types/user.ts
Labels: feature

#20 feat : [7] 버튼 공통 컴포넌트 생성
  package-lock.json
  package.json
  src/App.tsx
  src/components/banner.tsx
  src/components/buddy/buddyButton.tsx
  src/components/buddy/buddyStart.tsx
  src/components/button/confirmButton.tsx
  src/components/progressBar.tsx
  src/pages/buddyPage.tsx
  src/pages/home-page.tsx
Labels: feature

#22 feat : [8] 버디 시작페이지, 리뷰 기반 수정
  src/App.tsx
  src/assets/images/buddyStart.svg
  src/assets/images/nugul.svg
  src/components/buddy/buddyStart.tsx
  src/components/button/confirmButton.tsx
  src/pages/buddy-page.tsx
  src/pages/buddyPage.tsx
  src/services/apis/user.service.ts
Labels: feature

#24 feat : [9] 마이페이지 및 편집 디자인
  src/App.tsx
  src/assets/images/buddyImg.png
  src/assets/images/honbabImg.png
  src/components/header.tsx
  src/components/mypage/editInform/edit-inform.tsx
  src/components/mypage/guide.tsx
  src/components/mypage/matching-info.tsx
  src/pages/my-page-edit.tsx
  src/pages/my-page.tsx
  src/theme.ts
  src/types/mypage/css.ts
  src/types/mypage/mypage.ts
Labels: feature, refactor

#26 Feature/10: 버디 매칭 페이지 디자인 완료
  src/assets/images/notice.svg
  src/components/buddy/buddyButton.tsx
  src/components/buddy/buddyStart.tsx
  src/components/buddy/matching/buddyFinal5.tsx
  src/components/buddy/matching/buddyGender1.tsx
  src/components/buddy/matching/buddyGrade4.tsx
  src/components/buddy/matching/buddyMajor2.tsx
  src/components/buddy/matching/buddyType3.tsx
  src/components/button/confirmButton.tsx
  src/components/header/buddyHeader.tsx
  src/components/modals/alertModal.tsx
  src/pages/buddy-page.tsx
  src/services/apis/buddy.service.ts
  src/store/useBuddyStore.tsx
  src/styles/buddy-styles.ts
Labels: feature
